@startuml
skinparam style strictuml
skinparam monochrome true

Activate User
Activate DREAM

User->DREAM : openHomePage()

User<--DREAM: HomePage

User->DREAM: SelectOpenRequest(Request)

User<--DREAM: RequestForm

User->DREAM: closeRequest()

DREAM->Users: broadcastCloseRequest(Request)
Activate Users
DREAM<--Users
Deactivate Users

DREAM-->User: confirmation


@enduml