@startuml
skinparam style strictuml
skinparam monochrome true

Activate Agronomist
Activate DREAM

Agronomist->DREAM : OpenHomePage()

Agronomist<--DREAM: HomePage


Agronomist->DREAM : OpenDailyPlanListPage()

Agronomist<--DREAM: DailyPlanPage

Agronomist->DREAM: selectPlanFromList(Date)
DREAM-->Agronomist: dailyPlan

Agronomist->DREAM: selectSlot(Farmer)

loop 
alt select time selectSlot

Agronomist->DREAM: changeFarmer(Farmer)
DREAM-->Agronomist: updateDailyPlanPage

else select Farmer: changeTime

Agronomist->DREAM: shiftTimeSlot(time, time)
DREAM-->Agronomist: updateDailyPlanPage

end
end

@enduml