@startuml

skinparam style strictuml
skinparam monochrome true

(*) --> "show global statistics"
-->(*)

"show global statistics"-->"select the period of interest"
-->(*)


"select the period of interest"-->"filter data by area/agronomist"
"filter data by area/agronomist"-->"select ranking (best worst/performances)"

"select the period of interest"-->"select ranking (best worst/performances)"
-->(*)






@enduml