

@startuml
'!theme cerulean
'!theme materia-outline
'skinparam style strictuml
'skinparam monochrome true
'skinparam RoundCorner 15
'skinparam Linetype polyline
'skinparam Linetype ortho
left to right direction
skinparam componentStyle uml2

rectangle {

    rectangle #LightSkyBlue {
        
        
        component "Daily Plan Manager"#white{

        '---------------------------------
        ' set colorColor
        [Daily Plan Handler]#white
        [Visit Handler]#white
        [Message Dispatcher]#white
        
        '---------------------------------

        }

        Interface "Daily Plan Manager Interface" as PlanInt
        Interface "Query Interface" as QueryInt
        
        
        [Daily Plan Handler]-d-(QueryInt
        [Visit Handler]-d-(QueryInt
        [Message Dispatcher]-d-(QueryInt


        [Daily Plan Handler]-u-PlanInt
        [Visit Handler]-u-PlanInt
        [Message Dispatcher]-u-PlanInt

        [Daily Plan Handler]--[Visit Handler]
        [Visit Handler]--[Message Dispatcher]
        [Daily Plan Handler]--[Message Dispatcher]
    }
}





@enduml