@startuml
'skinparam style strictuml
'skinparam monochrome true
skinparam actorStyle awsome

actor Farmer #Coral
participant WebApp #Coral
participant WebServer #LightSkyBlue
'participant FarmerManager #LightSkyBlue
'participant DataMiner #LightSkyBlue
'participant DailyPlanManager #LightSkyBlue
participant ForumManager #LightSkyBlue
'participant ForumManager #LightSkyBlue
'participant WeatherForecastManager #LightSkyBlue

participant QueryManager #LightSkyBlue
participant DBMS

'participant WeatherForecastService #ADD1B2

Activate Farmer
Activate WebApp

Farmer->WebApp: clickCreatePostButton()

WebApp-->Farmer: NewPostForm

Farmer->WebApp: clickSubmitPostForm()

WebApp->WebServer: createNewPost(Message)
Activate WebServer
WebServer->ForumManager: dispatch
Activate ForumManager

ForumManager->QueryManager: updatePost(Discussion, Post)
Activate QueryManager

QueryManager->DBMS: RunQuery()

Activate DBMS

DBMS-->QueryManager : 

Deactivate DBMS
QueryManager-->ForumManager: 

Deactivate QueryManager

ForumManager-->WebServer

Deactivate ForumManager
WebServer-->WebApp: DiscussionPage
Deactivate WebServer
WebApp-->Farmer: DiscussionPage





@enduml